# Generated by Django 3.2.8 on 2022-01-31 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20220131_2234'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FollowPairs',
            new_name='FollowPair',
        ),
    ]
