# Generated by Django 3.2.8 on 2021-12-16 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20211215_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='starting_bid',
            field=models.IntegerField(default=None, max_length=32),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='auction',
            name='owner',
        ),
        migrations.AddField(
            model_name='auction',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auctions.user'),
            preserve_default=False,
        ),
    ]
