# Generated by Django 3.2.8 on 2021-12-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_comment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='image_link',
            field=models.CharField(default=None, max_length=128),
        ),
    ]
