# Generated by Django 3.2.8 on 2021-12-17 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auction_image_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actioneer', to=settings.AUTH_USER_MODEL),
        ),
    ]
