# Generated by Django 3.2.8 on 2021-12-19 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auction_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='winner',
        ),
    ]
