# Generated by Django 3.2.8 on 2021-12-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_remove_auction_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='winner',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
