# Generated by Django 3.2.8 on 2021-12-19 16:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auction_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='winner',
        ),
        migrations.AlterField(
            model_name='auction',
            name='image_link',
            field=models.CharField(blank=True, default=None, max_length=128),
        ),
        migrations.AlterField(
            model_name='auction',
            name='watchlist',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
